{
 "title": "CPI Monitoring - Messages",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "tenant_name",
    "label": "Tenant",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Kangoolutions GmbH",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CPI Monitoring\n\nCPI Monitor is an open source contribution and initially designed by Kangoolutions GmbH. Feel free to contribute and share your thoughts on Github or via email to cpi-monitoring@kangoolutions.com."
   }
  },
  {
   "title": "Processed Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `` | logfmt | label_format level=log_level [1h]))"
    }
   ]
  },
  {
   "title": "Failed Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `status=FAILED` | logfmt [1h]))"
    }
   ]
  },
  {
   "title": "Other Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} != `status=FAILED` != `status=COMPLETED` | logfmt [1h]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "targets": [
    {
     "expr": "sum(count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `` | logfmt | status = `FAILED` [$__auto]))"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "sum by(name) (count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `` | logfmt | label_format level=log_level [$__auto]))"
    }
   ]
  },
  {
   "title": "TOTAL Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `` | logfmt | status != `DISCARDED` | status != `PROCESSING` [$__auto]))"
    }
   ]
  },
  {
   "title": "CPI Runs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "sum by(log_level) (count_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `` | logfmt [$__auto]))"
    }
   ]
  },
  {
   "title": "Max duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "max_over_time({env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"} |= `duration_ms` | logfmt | unwrap duration_ms [$__auto]) by (name)"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "table",
   "gridPos": { "h": 20, "w": 23, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "{env=~\"(${env:pipe})\", tenant_name=~\"(${tenant_name:pipe})\", type=\"INTEGRATION_FLOW\"}| logfmt | label_format level=log_level"
    }
   ]
  }
 ]
}