{
 "title": "CPI Monitoring - Integration Flows",
 "tags": [ "integration flow" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({platform=\"cpi\"},env)"
    }
   },
   {
    "name": "tenant_name",
    "label": "Tenant Name",
    "query": {
     "query": "label_values({env=~\"(${env:pipe})\", platform=\"cpi\"},tenant_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kangoolutions GmbH",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# CPI Monitoring\n\nThis CPI Monitoring Dashboard is designed by Kangoolutions GmbH\nFor markdown syntax help: [commonmark.org/help](https://commonmark.org/help/)"
   }
  },
  {
   "title": "Deployed Integration Flows",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"})"
    }
   ]
  },
  {
   "title": "Failed Deployings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"}) == 0"
    }
   ]
  },
  {
   "title": "Deployment Status",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 7, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum by(iflow) (INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}