{
 "title": "CPI Monitoring - Messages",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "tenant_name",
    "label": "Tenant",
    "query": {}
   },
   { "name": "Filters" },
   {
    "name": "IFlow",
    "label": "IFlow",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Kangoolutions GmbH",
   "type": "text",
   "gridPos": { "h": 5, "w": 17, "x": 0, "y": 0 },
   "options": {
    "content": "# CPI Monitoring\n\nCPI Monitor is an open source contribution and initially designed by Kangoolutions GmbH. Feel free to contribute and share your thoughts on Github or via email to cpi-monitoring@kangoolutions.com."
   }
  },
  { "type": "library-panel-ref", "gridPos": { "h": 3, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Processed Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `` | logfmt | label_format level=log_level [1h]))"
    }
   ]
  },
  {
   "title": "Successful Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `status=COMPLETED` | logfmt [1h]))"
    }
   ]
  },
  {
   "title": "Failed Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `status=FAILED` | logfmt [1h]))"
    }
   ]
  },
  {
   "title": "Processed Messages",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(name, package_id, level) (count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `` | logfmt | label_format level=log_level [$__auto]))"
    }
   ]
  },
  {
   "title": "Retry Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `status=RETRY` | logfmt [1h]))"
    }
   ]
  },
  {
   "title": "Other Messages",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} != `status=FAILED` != `status=COMPLETED` != `status=RETRY` | logfmt [1h]))"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `` | logfmt | status = `FAILED` [$__auto]))"
    }
   ]
  },
  {
   "title": "TOTAL Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `` | logfmt | status != `DISCARDED` | status != `PROCESSING` [$__auto]))"
    }
   ]
  },
  {
   "title": "CPI Runs by LogLevel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(log_level) (count_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `` | logfmt [$__auto]))"
    }
   ]
  },
  {
   "title": "Max duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by(iflow) (max_over_time({service_name=~\"(${tenant_name:pipe})\", deployment_environment=~\"(${env:pipe})\", service_namespace=~\"CPI\", service_instance_id=~\"(${IFlow:pipe})\"} |= `duration_ms` | logfmt | unwrap duration_ms [$__auto]))"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\"} | logfmt | label_format level=log_level"
    }
   ]
  }
 ]
}