{
 "title": "CPI Monitoring - Integration Flows",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Environment",
    "label": "Environment",
    "query": {
     "query": "label_values({service_namespace=\"CPI\"},deployment_environment)"
    }
   },
   {
    "name": "Tenant",
    "label": "Tenant",
    "query": {
     "query": "label_values({deployment_environment=~\"(${Environment:pipe})\", service_namespace=\"CPI\"},service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kangoolutions GmbH",
   "type": "text",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "# CPI Monitoring\n\nThis CPI Monitoring Dashboard is designed by [Kangoolutions GmbH](https://kangoolutions.com)\nYou agree to our license agreement. Please check [Dashboard Page](https://grafana.com/grafana/dashboards/20742) for updates."
   }
  },
  { "type": "library-panel-ref", "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Deployment Status",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by(iflow) (integration_flow_is_running_total_count{deployment_environment=~\"(${Environment:pipe})\", service_name=~\"(${Tenant:pipe})\", service_namespace=\"CPI\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed Integration Flows",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(integration_flow_is_running_total_count{deployment_environment=~\"(${Environment:pipe})\", service_namespace=\"CPI\", service_name=~\"(${Tenant:pipe})\"})"
    }
   ]
  },
  {
   "title": "Failed Deployings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(integration_flow_is_running_total_count{deployment_environment=~\"(${Environment:pipe})\", service_namespace=\"CPI\", service_name=~\"(${Tenant:pipe})\"} == 0)"
    }
   ]
  },
  {
   "title": "Deploying",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(integration_flow_is_running_total_count{deployment_environment=~\"(${Environment:pipe})\", service_namespace=\"CPI\", service_name=~\"(${Tenant:pipe})\"} == 0.5)"
    }
   ]
  }
 ]
}