{
 "title": "CPI Monitoring - Integration Flows",
 "tags": [ "integration flow" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {
     "query": "label_values({platform=\"cpi\"},env)"
    }
   },
   {
    "name": "tenant_name",
    "label": "Tenant Name",
    "query": {
     "query": "label_values({env=~\"(${env:pipe})\", platform=\"cpi\"},tenant_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Kangoolutions GmbH",
   "type": "text",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "options": {
    "content": "# CPI Monitoring\n\nThis CPI Monitoring Dashboard is designed by [Kangoolutions GmbH](https://kangoolutions.com)\nYou agree to our license agreement. Please check [Dashboard Page](https://grafana.com/grafana/dashboards/20742) for updates."
   },
   "targets": [
    {}
   ]
  },
  { "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 } },
  {
   "title": "Deployment Status",
   "type": "state-timeline",
   "gridPos": { "h": 24, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "max by(iflow) (INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deployed Integration Flows",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"})"
    }
   ]
  },
  {
   "title": "Failed Deployings",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"}) == 0"
    }
   ]
  },
  {
   "title": "Deploying",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(INTEGRATION_FLOW_IS_RUNNING_metric{env=~\"(${env:pipe})\", platform=\"cpi\", tenant_name=~\"(${tenant_name:pipe})\"}) == 0.5"
    }
   ]
  }
 ]
}