{
 "title": "CPI Monitoring - Ressource Usage",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": {}
   },
   {
    "name": "tenant_name",
    "label": "Tenant",
    "query": {}
   }
  ]
 },
 "panels": [
  { "title": "Kangoolutions GmbH", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 15, "x": 0, "y": 0 } },
  { "type": "library-panel-ref", "gridPos": { "h": 4, "w": 8, "x": 15, "y": 0 } },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "CPI_DB_MEMORY_CONSUMPTION_total_bytes{deployment_environment=~\"(${env:pipe})\", service_namespace=\"CPI\", service_name=~\"(${tenant_name:pipe})\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPI_DB_MEMORY_CONSUMPTION_bytes{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\", service_namespace=\"CPI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Max Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "CPI_MESSAGE_MAX_BYTES_bytes{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\", service_namespace=\"CPI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastore Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "CPI_DATASTORE_USAGE_count{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\", service_namespace=\"CPI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "CPI_NUMBER_MESSAGES_count{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\", service_namespace=\"CPI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(CPI_DB_CONNECTIONS_USAGE_count{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\", service_namespace=\"CPI\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "CPI_DB_CONNECTIONS_USAGE_total_count{deployment_environment=~\"(${env:pipe})\", service_name=~\"(${tenant_name:pipe})\", service_namespace=\"CPI\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}